# Generated by Django 3.2 on 2021-04-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=45)),
                ('total_items_carousel', models.IntegerField(max_length=45)),
                ('admin_name', models.CharField(max_length=45)),
                ('admin_email', models.CharField(max_length=45)),
            ],
        ),
    ]
