# Generated by Django 3.2 on 2021-04-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='group_logo',
            field=models.ImageField(default='static/logo.png', upload_to='static'),
        ),
    ]
