# Generated by Django 3.2 on 2021-05-01 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_configuration_group_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='total_items_carousel',
        ),
    ]
