# Generated by Django 3.2 on 2021-05-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210502_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitemelement',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
