# Generated by Django 3.2 on 2021-05-06 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210502_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='menuitemelement',
            options={'ordering': ['pk']},
        ),
    ]
