# Generated by Django 3.2 on 2021-05-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210506_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='group_logo',
            field=models.ImageField(default='/static/img/logo.png', upload_to='static/img'),
        ),
    ]
