# Generated by Django 3.2 on 2021-05-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitemelement',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
