# Generated by Django 3.2 on 2021-05-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_configuration_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='group_logo',
            field=models.ImageField(upload_to='logo'),
        ),
    ]
