# Generated by Django 3.2 on 2021-05-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_configuration_group_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='group_logo',
            field=models.ImageField(upload_to='img'),
        ),
    ]
