# Generated by Django 4.0.3 on 2022-04-02 14:27

import apps.blog.models
import config.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('image', models.ImageField(storage=config.storage.OverwriteStorage(), upload_to=apps.blog.models.post_image_filename, verbose_name='Imagen (1200x400)')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Fecha última actualización')),
                ('content', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='Estado')),
                ('carousel_item', models.BooleanField(default=False, verbose_name='Mostrar en la página de inicio')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
