# Generated by Django 3.2 on 2021-05-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210506_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/static/img/blog/default.jpg', upload_to='static/img/blog'),
        ),
    ]
