# Generated by Django 3.2 on 2021-05-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carousel_item',
            field=models.BooleanField(default=False, verbose_name='show item in carousel'),
        ),
    ]
