# Generated by Django 3.2 on 2021-05-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
