# Generated by Django 3.2 on 2021-05-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_publication_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(default='/static/img/research/publications/default.jpg', upload_to='static/img/research/publications'),
        ),
    ]
