# Generated by Django 3.2 on 2021-05-06 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_publication_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researcharea',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='researcharea',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researcharea',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researcharea',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researcharea',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
