# Generated by Django 3.1.3 on 2020-11-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aperture_size', models.FloatField()),
                ('aperture_position', models.FloatField()),
                ('wavelenth', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_material', models.CharField(max_length=6)),
                ('img_material', models.CharField(max_length=6)),
                ('obj_position', models.FloatField()),
                ('img_position', models.FloatField()),
                ('max_rho', models.FloatField()),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raytracing.system')),
            ],
        ),
    ]
