# Generated by Django 3.1.3 on 2020-11-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raytracing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surface',
            name='position',
            field=models.FloatField(default=0),
        ),
    ]
