# Generated by Django 3.1.3 on 2020-11-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raytracing', '0002_surface_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='wavelenth',
            new_name='wavelength',
        ),
    ]
