# Generated by Django 3.1.3 on 2020-11-23 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raytracing', '0003_auto_20201123_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surface',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surfaces', to='raytracing.system'),
        ),
    ]
