# Generated by Django 3.1.3 on 2020-11-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raytracing', '0005_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='surface',
            name='img_material',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='surface',
            name='obj_material',
            field=models.CharField(max_length=8),
        ),
    ]
