# Generated by Django 3.1.3 on 2020-11-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raytracing', '0007_auto_20201123_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
