# Generated by Django 3.1.3 on 2020-11-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raytracing', '0008_auto_20201123_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='object_height',
            field=models.FloatField(default=0),
        ),
    ]
