# Generated by Django 3.2 on 2021-05-28 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='/static/img/research/default.jpg', upload_to='static/img/research')),
                ('content', models.TextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('full_description', models.TextField(blank=True, null=True)),
                ('journal', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='static/img/research/publications')),
                ('image', models.ImageField(default='/static/img/research/publications/default.jpg', upload_to='static/img/research/publications')),
                ('doi', models.URLField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researcharea')),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
