# Generated by Django 3.2 on 2021-05-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(default='/media/research/publications/img/default.jpg', upload_to='media/research/publications/img'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='media/research/publications/pdf'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='image',
            field=models.ImageField(default='/media/research/img/default.jpg', upload_to='media/research/img'),
        ),
    ]
