# Generated by Django 3.2 on 2021-05-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20210528_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(default='0', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
