# Generated by Django 3.2 on 2021-05-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_publication_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='slug',
        ),
    ]
